### ISSUE TITLE
Confusion in Random Feature Posterior

### ISSUE THREAD

**Issue by ssydasheng** [zi-w/Max-value-Entropy-Search#2]
https://github.com/zi-w/Max-value-Entropy-Search/blob/885030574233c95891ddbfb23ff0a8cb1790fe5a/utils/sampleMaximumValues.m#L47

What's the use for this line? `D` itself is already the eigendecomposition of `Z^t Z + \sigma^2 I`, it looks to me that `R=1./D`. Can you please clarify this ?

**Comment by zi-w** [comment]
Hi, you can find the detailed explanation of this method at Appendix B.2 of http://www.jmlr.org/papers/volume9/seeger08a/seeger08a.pdf
