### ISSUE TITLE
mex chol2invchol.c for Windows

### ISSUE THREAD

**Issue by RomanFoell** [zi-w/Max-value-Entropy-Search#4]
Hello,

is it possible, that you can upload a mex file for windows for chol2invchol.c.
I tried several ways to mex it by myself, but I was not successful.

Thanks in advance.

Roman

**Comment by yiminzme** [comment]
Hi, I have successfully run the example.m on {Windows 10, Matlab R2019b} with MinGW 6.3, MSYS.

To get a working mex file of chol2invchol.c for your Windows environment, 
(1) you first need to install a MinGW for your Matlab. Here is a tutorial on installing a correct [MinGW](https://www.youtube.com/watch?v=12XRTUqG94Y) for Matlab. 
(2) Then, I downloaded [MSYS](http://www.mingw.org/wiki/MSYS) and link it to the MinGW for Matlab.
(3) Next, download a [GSL library](t.ly/DmuS) (I used gsl-2.1.tar.gz) and build the library using the MSYS.
(4) Finally, open Matlab and run 
`mex chol2invchol.c "-I<path_to_gsl_directory>" "-L<path_to_gsl_directory>\cblas\.libs" "-L<path_to_gsl_directory>\.libs" -lgsl -lgslcblas` 
in the utils folder.
For example, run 
`mex chol2invchol.c "-IC:\Users\username\Downloads\gsl-2.1" "-LC:\Users\username\Downloads\gsl-2.1\cblas\.libs" "-LC:\Users\username\Downloads\gsl-2.1\.libs" -lgsl -lgslcblas`.

Good luck.

**Comment by yiminzme** [comment]
![20200419capture](https://user-images.githubusercontent.com/11984137/79692851-06dde000-829a-11ea-86da-b9ed9c1c1541.jpg)

**Comment by yiminzme** [comment]
![example.m](https://user-images.githubusercontent.com/11984137/79692883-3b519c00-829a-11ea-8491-ca12531fba3d.jpg)

**Comment by zi-w** [comment]
Thank you, @yiminzme! I'll close this issue for now.

**Comment by wyx-agoupidao** [comment]
> Hi, I have successfully run the example.m on {Windows 10, Matlab R2019b} with MinGW 6.3, MSYS.
> 
> To get a working mex file of chol2invchol.c for your Windows environment,
> (1) you first need to install a MinGW for your Matlab. Here is a tutorial on installing a correct [MinGW](https://www.youtube.com/watch?v=12XRTUqG94Y) for Matlab.
> (2) Then, I downloaded [MSYS](http://www.mingw.org/wiki/MSYS) and link it to the MinGW for Matlab.
> (3) Next, download a [GSL library](t.ly/DmuS) (I used gsl-2.1.tar.gz) and build the library using the MSYS.
> (4) Finally, open Matlab and run
> `mex chol2invchol.c "-I<path_to_gsl_directory>" "-L<path_to_gsl_directory>\cblas\.libs" "-L<path_to_gsl_directory>\.libs" -lgsl -lgslcblas`
> in the utils folder.
> For example, run
> `mex chol2invchol.c "-IC:\Users\username\Downloads\gsl-2.1" "-LC:\Users\username\Downloads\gsl-2.1\cblas\.libs" "-LC:\Users\username\Downloads\gsl-2.1\.libs" -lgsl -lgslcblas`.
> 
> Good luck.

Excuse me, here I met some problem in step (3): how to build the GSL library via the MSYS2? MATLAB needs a ".lib" file as library on Windows instead of a ".a" file on Linux. Now I don't know how to create the ".lib" file.
