### ISSUE TITLE
MES for discrete domains

### ISSUE THREAD

**Issue by giotre** [zi-w/Max-value-Entropy-Search#5]
Dear Dr. Wang,
I found your paper about MES really interesting. I have a question about it: since I'm working on discrete and scattered search spaces with "real" black box functions, is your code suitable for this as it is or do you suggest to adapt it? In particular, I refer to all the optimization scripts: can I avoid all the gradient-based searches with **fmincon**, just computing _effectively_ the acquisition function in all the domain points? 
Thank you in advance.

**Comment by zi-w** [comment]
Thanks for your interest in this work. You can replace the continuous optimization for acquisition functions with returning the optimal from evaluations on a discrete set of points. It should be an easy fix. Please let me know if you have other questions.
